#
# Example pair.io config.  
# https://github.com/zkim/pairio-config-example
#

# Quickstarts are pre-packaged instances, which allow you to get up
# and running in a short amount of time.  Pair.io will examine your
# repo and try to pick the correct one.
#
# You can force a particular quickstart like so:
#quickstart: empty # | ruby19 | rails3 | nodejs | clojure

# Pair.io gives you fine-grained control over what we provision for
# you. Here's the full set of config options:

image-id: ami-cef405a7
size: large # | micro | small | large
inbound-ports: 
  - 22
provision: none # none | sh | chef



